# Generated by Django 5.2.7 on 2025-10-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Diaria", "Diaria"),
                    ("Semanal", "Semanal"),
                    ("Mensual", "Mensual"),
                ],
                default="Diaria",
                max_length=50,
            ),
        ),
    ]
